### ISSUE TITLE
Could you release a scala 2.11 version?

### ISSUE THREAD

**Issue by gbougeard** [nicolasstucki/multisets#2]

**Comment by ShaneDelmore** [comment]
I would appreciate this as well.  I tried to use the scala 2.10 version in my scala 2.11 project but ended up with errors trying to run just the basic examples from the readme file.

**Comment by axel22** [comment]
+1 :)

**Comment by nicolasstucki** [comment]
I started the creation of the 2.11.x version. It may take a week or so to have it released, because I want to fix a couple of bugs first. Meanwhile you could compile it locally to use it.

Regarding the basic examples in the readme I saw that there where bugs in it and fixed them.

**Comment by ShaneDelmore** [comment]
That is great news, thanks for the update.

**Comment by Blaisorblade** [comment]
Hi @nicolasstucki! Any updates on this?

**Comment by nicolasstucki** [comment]
It should be ready to be published, but I do not remember how to publish the artefacts.
@axel22 could you point me to the documentation that I used the first time.

**Comment by axel22** [comment]
I believe it was this:

http://central.sonatype.org/pages/ossrh-guide.html

Or this:

http://central.sonatype.org/pages/releasing-the-deployment.html

In any case, you need to call publish from SBT, then go to Sonatype UI and manually close the staging version there, then release the new version.

**Comment by nicolasstucki** [comment]
I released version 0.2 of the multisets for Scala with support for 2.10 and 2.11.
@Blaisorblade

**Comment by Blaisorblade** [comment]
Thanks a lot, I'll give it a try soon!
