### ISSUE TITLE
Request for a new release post 0.3

### ISSUE THREAD

**Issue by sageserpent-open** [nicolasstucki/multisets#25]
Hi Nicolas,

It would be good to get the recent bug fixes published - from #24  etc.

Also, could you provide a Scala 2.12 build for this?

I'm happy to help with setting up and testing the 2.12 build if you want me to do this as a PR from my side.

**Comment by nicolasstucki** [comment]
Scala 2.12 is a good idea. If you can help me setting up the build I would greatly appreciate it.

**Comment by sageserpent-open** [comment]
Great - let me get something together for 2.12, then I'll raise a PR.

**Comment by sageserpent-open** [comment]
PR #26 is in the works....

**Comment by nicolasstucki** [comment]
Nice

**Comment by armanbilge** [comment]
Any idea when a 2.12 build will be published on Maven or what is left to be done? This is the last dependency I need so that I can bump one of my projects to 2.12. Thanks!

**Comment by nicolasstucki** [comment]
I just published version 0.4 with 2.12. It should be up in a short time.

**Comment by sageserpent-open** [comment]
Thanks, Nicolas.
