### ISSUE TITLE
Clarify the license

### ISSUE THREAD

**Issue by yoriyuki** [nicolasstucki/multisets#4]
Presumably you intend to make your Bag public under an open-source license, but I cannot find an official statement concerning a license.  Please clarify it.

**Comment by nicolasstucki** [comment]
Yes, you are right, it is intended as open-source. I've added that statement to the description of the project. I hope this is enough for your needs, if not please tell me and i'll add a more complete statement.

**Comment by yoriyuki** [comment]
Thank you for adding a notice.  Could you put the statement what sort of licenses (BSD, GPL  etc) you choose in REAEMD.md, and the complete legal statements in LICENSE.md?

Sorry for raising a boring legal issue but I cannot use your code without checking whether using it is legal.

**Comment by nicolasstucki** [comment]
I've added a BSD licence, you can find it in https://github.com/nicolasstucki/multisets/blob/2.11.x/LICENCE

**Comment by axel22** [comment]
Also, it's good to always make sure that your license corresponds to the one in the `build.sbt` file (which is the [case for multisets](https://github.com/nicolasstucki/multisets/blob/2.11.x/build.sbt#L37)).
