### ISSUE TITLE
HashBag is not serializable

### ISSUE THREAD

**Issue by nfsantos** [nicolasstucki/multisets#9]
I'm evaluating the multisets library for use in our project. In our application, we need to send bag objects over the network. For the time being, we are using Java Serialization. But it seems that serialization is not supported. Is this intended? Since collections are typically serializable, I was expecting the Bag objects also to be serializable.

As an example, the code below fails with a NotSerializableException.

``` scala
import java.io.{ByteArrayOutputStream, ObjectOutputStream}
import scala.collection.immutable.Bag

implicit val b = Bag.configuration.compact[Int]
val bag = Bag(1, 2, 3)
val os = new ObjectOutputStream(new ByteArrayOutputStream())
os.writeObject(bag)
os.close()
```

```
java.io.NotSerializableException: scala.collection.immutable.HashedBagConfiguration$HashedMultiplicityBagConfiguration
    at java.io.ObjectOutputStream.writeObject0(Bags.sc0.tmp:1180)
    at java.io.ObjectOutputStream.defaultWriteFields(Bags.sc0.tmp:1544)
    at java.io.ObjectOutputStream.writeSerialData(Bags.sc0.tmp:1505)
    at java.io.ObjectOutputStream.writeOrdinaryObject(Bags.sc0.tmp:1428)
    at java.io.ObjectOutputStream.writeObject0(Bags.sc0.tmp:1174)
    at java.io.ObjectOutputStream.writeObject(Bags.sc0.tmp:344)
    at #worksheet#.#worksheet#(Bags.sc0.tmp:32)
```

**Comment by nicolasstucki** [comment]
It is not currently supported. Unfortunately the bag uses some functions the configuration that may not be serializable. Although in theory it should be possible to serialize the default configuration like the the one that you are using (i.e. only have serialization of predefined configurations).

**Comment by nfsantos** [comment]
Thanks for the clarification. Any chance that this may be supported in the near future? How much work do you think it would be required to implement this?

**Comment by nicolasstucki** [comment]
I would say not for the need future. But there is a simple workaround that you could use: convert the bad to a list of Tuple2 where that contains the elements and its count (or multiplicity) and then serialize that object. You can then reconstruct the bag from this representation. I hope that this is a solution that works for your use case. If not, could you describe a bit more your use case.
